openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Authentication
  description: 認証関連のAPI
paths:
  /api/auth/logout:
    post:
      tags:
      - Authentication
      summary: ログアウト
      description: 現在のセッションからログアウトします
      operationId: logout
      responses:
        "200":
          description: ログアウト成功
          content:
            '*/*':
              schema:
                type: object
  /api/auth/login:
    post:
      tags:
      - Authentication
      summary: ログイン
      description: ユーザー名とパスワードでログインし、セッションを開始します
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "400":
          description: 無効なユーザー名またはパスワード
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: ログイン成功
          content:
            '*/*':
              schema:
                type: object
  /api/auth/change-password:
    post:
      tags:
      - Authentication
      summary: パスワード変更
      description: 現在のパスワードを確認した上で、新しいパスワードに変更します
      operationId: changePassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordRequest"
        required: true
      responses:
        "400":
          description: 無効なパスワードまたはユーザーが見つかりません
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: パスワード変更成功
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    LoginRequest:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
          description: ユーザー名
          example: user1
        password:
          type: string
          description: パスワード
          example: password123
      description: ログインリクエスト
    ChangePasswordRequest:
      required:
      - newPassword
      - oldPassword
      type: object
      properties:
        oldPassword:
          type: string
          description: 現在のパスワード
          example: oldPassword123
        newPassword:
          type: string
          description: 新しいパスワード
          example: newPassword123
      description: パスワード変更リクエスト
