/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq;


import com.example.demo.jooq.tables.RevokedTokens;
import com.example.demo.jooq.tables.Roles;
import com.example.demo.jooq.tables.UserRoles;
import com.example.demo.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.revoked_tokens</code>.
     */
    public static final RevokedTokens REVOKED_TOKENS = RevokedTokens.REVOKED_TOKENS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
